version: "3.8"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
  app:
    build:
      context: .
    ports:
      - "10000:8080"
    environment:
      - DB_HOST=db
    depends_on:
      - db
    links:
      - db
